### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by MTRNord** [pslobo/dockerized-certbot#2]
Can this as a standelone cert generator used with docker-compose?

**Comment by pslobo** [comment]
Yeah, pretty much. In fact, this was initially created to to used [here](https://github.com/psychok7/django-yadpt-starter) and we're using it successfully in a majority of our current projects. 

You can take a look at how we've done it in the above repo and I'm sure that will guide you. If you still need some help let me know.
